// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvents.proto

package com.example.grpc.server.grpcserver;

public interface ActionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.ActionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string microservice = 1;</code>
   * @return The microservice.
   */
  java.lang.String getMicroservice();
  /**
   * <code>string microservice = 1;</code>
   * @return The bytes for microservice.
   */
  com.google.protobuf.ByteString
      getMicroserviceBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string resource = 3;</code>
   * @return The resource.
   */
  java.lang.String getResource();
  /**
   * <code>string resource = 3;</code>
   * @return The bytes for resource.
   */
  com.google.protobuf.ByteString
      getResourceBytes();

  /**
   * <code>string responseType = 4;</code>
   * @return The responseType.
   */
  java.lang.String getResponseType();
  /**
   * <code>string responseType = 4;</code>
   * @return The bytes for responseType.
   */
  com.google.protobuf.ByteString
      getResponseTypeBytes();

  /**
   * <code>string timestamp = 5;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
